// export const ADD_ENTRY = 'ADD_ENTRY';
export const EDIT_ENTRY = 'EDIT_ENTRY';
export const FILTER_BY_YEAR = 'FILTER_BY_YEAR';
export const SET_YEAR = 'SET_YEAR';

export const ADD_ENRTY_REQUEST = 'ADD_ENRTY_REQUEST';
export const ADD_ENRTY_SUCCESS = 'ADD_ENRTY_SUCCESS';
export const ADD_ENRTY_FAIL = 'ADD_ENRTY_FAIL';

export const FETCH_ENRTY_REQUEST = 'FETCH_ENRTY_REQUEST';
export const FETCH_ENRTY_SUCCESS = 'FETCH_ENRTY_SUCCESS';
export const FETCH_ENRTY_FAIL = 'FETCH_ENRTY_FAIL';
export const FETCH_ENRTY_RESET = 'FETCH_ENRTY_RESET';

export const ENTRIES_LIST_REQUEST = 'ENTRIES_LIST_REQUEST';
export const ENTRIES_LIST_SUCCESS = 'ENTRIES_LIST_SUCCESS';
export const ENTRIES_LIST_FAIL = 'ENTRIES_LIST_FAIL';

export const DELETE_ENRTY_REQUEST = 'DELETE_ENRTY_REQUEST';
export const DELETE_ENRTY_SUCCESS = 'DELETE_ENRTY_SUCCESS';
export const DELETE_ENRTY_FAIL = 'DELETE_ENRTY_FAIL';

export const EDIT_ENRTY_REQUEST = 'EDIT_ENRTY_REQUEST';
export const EDIT_ENRTY_SUCCESS = 'EDIT_ENRTY_SUCCESS';
export const EDIT_ENRTY_FAIL = 'EDIT_ENRTY_FAIL';
