// export const ADD_ENTRY = 'ADD_ENTRY';
export const FETCH_ENTRY = 'FETCH_ENTRY';
export const EDIT_ENTRY = 'EDIT_ENTRY';
export const DELETE_ENTRY = 'DELETE_ENTRY';
export const RESET_ENTRY = 'RESET_ENTRY';
export const FILTER_BY_YEAR = 'FILTER_BY_YEAR';
export const SET_YEAR = 'SET_YEAR';

export const ADD_ENRTY_REQUEST = 'ADD_ENRTY_REQUEST';
export const ADD_ENRTY_SUCCESS = 'ADD_ENRTY_SUCCESS';
export const ADD_ENRTY_FAIL = 'ADD_ENRTY_FAIL';

export const ENTRIES_LIST_REQUEST = 'ENTRIES_LIST_REQUEST';
export const ENTRIES_LIST_SUCCESS = 'ENTRIES_LIST_SUCCESS';
export const ENTRIES_LIST_FAIL = 'ENTRIES_LIST_FAIL';
